collections:
  explanations:
  teas:
    output: true
  orders:
    output: true
  packages:

defaults:
  - scope:
      path: ""
    values:
      title: "Projekt: Teegenuss"
      layout: "default"
  - scope:
      path: ""
      type: "orders"
    values:
      layout: "order"
  - scope:
      path: ""
      type: "teas"
    values:
      layout: "tea"