collections:
  glossary:
  teas:
    output: true
  orders:
    output: true
  packages:

defaults:
  - scope:
      path: ""
    values:
      title: "Projekt: Teegenuss"
      layout: "default"
  - scope:
      path: ""
      type: "teas"
    values:
      layout: "tea"

exclude:
  - ui-debug.log
  - firebase-debug.log